project_id = "mjcuvflvqgenujpfcoqw"

[functions.fitek-chat]
verify_jwt = false

[functions.shopify-storefront]
verify_jwt = false

[functions.generate-recipes]
verify_jwt = false

[functions.estimate-meal]
verify_jwt = false
