project_id = "mjcuvflvqgenujpfcoqw"

[functions.fitek-chat]
verify_jwt = true

[functions.shopify-storefront]
verify_jwt = false

[functions.generate-recipes]
verify_jwt = true

[functions.estimate-meal]
verify_jwt = true

[functions.shopify-webhook]
verify_jwt = false

[functions.generate-diet-plan]
verify_jwt = true

[functions.scan-meal]
verify_jwt = true
